### ISSUE TITLE
Allow user uploading of polygons for landscape profiles

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-web-client#193]
## Description
Allow user uploading of landscape polygons in GeoJSON format for landscape profiles.

**Comment by GabeBolton** [comment]
Two corrections to this issue, both from reading the client rather than assuming.

**1. "The first thing a reader sees" is wrong.** `featuredImage` does not appear in the
story viewer at all. Grepping `src/storyMap/` outside the editor, it is read in exactly two
places:

- `StoryMapGalleryCard.jsx` — the card in a gallery listing
- `storyMapHomeListItemUtils.js` — the home list row

both as `config?.featuredImage?.signedUrl || STORY_MAP_FALLBACK_IMAGE`, with
`featuredImage.description` as the alt text. So the payoff is that a converted story has a
**thumbnail in listings instead of the fallback placeholder** — worth having, since a wall
of identical placeholders is what a gallery of converted stories currently looks like, but
smaller than I claimed.

**2. `FeaturedImage.url` is typed `HttpUrl`, and nothing reads `url`.** Both client paths
read `signedUrl`; the editor falls back to `contentId`. Our re-uploaded media carries a
bucket-relative storage key, which `HttpUrl` will reject outright — so this is not purely a
placement rule as the issue says.

`Media.url` already has this exact problem solved, and its docstring says why:

> ``image``/``video``/``audio`` media that has been re-uploaded into Terraso's own storage
> carries the resulting bucket-relative storage key instead -- the real backend's own read
> path (``get_signed_url``) expects exactly that shape and cannot resolve an absolute URL.
> A single ``HttpUrl``-typed field can't hold both, so this is a plain ``str``.

`FeaturedImage.url` needs the same treatment, and the backend's signing path for featured
images should be checked the way #50 checked it for media — whether it signs from `url` at
all, or whether `contentId` is the field it populates from.

Scope is unchanged and still small, but it is a schema change plus a placement rule, not
just a placement rule. Worth confirming against the backend before starting, because "which
field does the backend sign from" is the question that decides the whole shape.

**Comment by DerekCaelin** [comment]
@GabeBolton Thanks for the comment! Did you mean to post this to a different issue?

**Comment by GabeBolton** [comment]
Yes, that was meant to be pointed at a private mirror with a different #193. Sorry for the confusion.
