### ISSUE TITLE
Implement call to end back-end sessions

### ISSUE THREAD

**Issue by cacarrara** [techmatters/terraso-web-client#281]
After https://github.com/techmatters/terraso-backend/pull/142 being merged, it'll be necessary to call the API `auth/logout` to also end the backend session. The reasoning of the new session is explained on the issue.

**Comment by josebui** [comment]
@cacarrara What will happen if the client doesn't call the logout endpoint? I am thinking about the possibility that the API is not available at the moment of the logout, should that prevent the logout? because if the process continue then the tokens will be removed from the client side and then the user will have to login again

**Comment by cacarrara** [comment]
> What will happen if the client doesn't call the logout endpoint?

The server session will be kept. Which means, access to `/admin` and `/oauth/authorize` will continue. I don't think it's a huge risk already because the sessions also expires after some time (currently 2 weeks, but we can decrease it).

Perhaps we can remove the client tokens only after a success response from API? What do you think?

**Comment by josebui** [comment]
@cacarrara If it expires automatically I think it is better to continue with the logout if the request fails, because that will not block the user from performing the desired action, and from our side it is not that bad since those rare failures side effects will be cleaned automatically with the automatic expiration eventually

**Comment by cacarrara** [comment]
Agreed. :+1:
