### ISSUE TITLE
User profile image is visible on staging but not on production.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#363]
Staging
<img width="128" alt="image" src="https://user-images.githubusercontent.com/10799815/170294109-11d321fb-defe-447b-9a83-35ff211e55a3.png">

Production
<img width="115" alt="image" src="https://user-images.githubusercontent.com/10799815/170294000-0a825bac-44bd-4e1d-ae7a-3c384b708327.png">

![image](https://user-images.githubusercontent.com/86784/171283749-4bcb8b7d-9622-4156-9d25-a015bd7ef566.png)

## Description
Throughout Terraso, the user profile image is visible on staging but not on production.

Could we push this change?

**Comment by paulschreiber** [comment]
This is not actually a staging vs production problem.

There are two things going on:

- when a user was deleted, their membership from a group was not deleted (fixed with https://github.com/techmatters/terraso-backend/pull/179)
- we only check for the picture the very first time you log in. if you created an account before the picture loading was written, your `profile_image` field will never be populated. @cacarrara is working on a fix for this. It will still required you to [remove Terraso from your Google third-party apps list](https://myaccount.google.com/permissions) once to fix this.
