### ISSUE TITLE
Color picker persists after selecting a color for data points

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#547]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10799815/193123010-ec8bdbf6-704a-43ed-b1fb-b1a75173940f.png">

## Description
On Mac, in Firefox, I selected a color for data points, then selected "next" without closing the color picker window. The color picker continues to persist.

## Steps To Reproduce

1. Select, "Make Map" in a landscape with a map-ready data file
2. Proceed to step 3. Appearance
3. Select a color from color swatch
4. Select "Next"

## Expected behavior
Color picker should disappear after selecting a color

## Actual behavior
Color picker continues until the window is closed

**Comment by paulschreiber** [comment]
@DerekCaelin That looks like the system color picker. Do you see the same behavior in other browsers?

**Comment by DerekCaelin** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/10799815/193125739-48319d52-4d2e-4fdb-a7f4-79e64d80a8aa.png">
Not in brave.

**Comment by shrouxm** [comment]
@DerekCaelin can you still reproduce this? we are using the web browser's built-in color picker for this component, which differs by OS & browser (i see a third, different color picker myself). we can't really fix any issues that arise from this because it's just a standard HTML element with no customization options.

i am inclined to close this issue, & maybe make a backlog issue to find an accessible color picker library to replace it with if we want a unified experience, or no follow-up issue if we are ok with accepting what comes from browsers' various default color picker elements. let me know your thoughts!

**Comment by DerekCaelin** [comment]
Agreed and closed
