### ISSUE TITLE
Long Group Names are Cropped

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#654]
![image](https://user-images.githubusercontent.com/10799815/211871736-da27646a-93f6-4fb1-bd0c-6828b8e323b3.png)

## Description
Within [the list of Terraso groups](https://app.terraso.org/groups), groups with long names are cropped

## Steps To Reproduce

1. Go to URL: https://app.terraso.org/groups
2. See issues

## Expected behavior
Wrapped text?

**Comment by paulschreiber** [comment]
@Hanal-code How do you want to handle these?
• hard truncate at end
• truncate at end with ellipses
• truncate in middle with ellipses
• horizontal scrolling within cell
• wrap (increase line height)
• something else?

**Comment by Hanal-code** [comment]
@paulschreiber My answer is to **truncate at end with ellipses** for group names, email address, and website as well. 

I'd also suggest to **widen the Group name column** instead of the same width for all three: Name, Email, Website. 
There are many ways to widen the name column.  First, can we try to apply the width of Actions column to Email and Website? That will widen the name column and the email & website is less important in this page. 

If it's not too much work, I'd suggest removing `https://` from the website. That will save some space as well.

**Comment by paulschreiber** [comment]
@DerekCaelin @Hanal-code Please verify this fix on staging.

**Comment by Hanal-code** [comment]
Verified that the name column width has been increased, so no names got cut off.

**Comment by Hanal-code** [comment]
However, Actions column is too narrow for Request to join button -- the left and right edge of button got cut off.

**Comment by paulschreiber** [comment]
@Hanal-code Does not reproduce on Chrome 109 for me at 100% zoom. I've made the column wider. Please re-verify on staging.
