### ISSUE TITLE
Group member management

### ISSUE THREAD

**Issue by josebui** [techmatters/terraso-web-client#97]
## Description
As a Terraso group manager I need to see, add and remove members.

**Comment by Hanal-code** [comment]
Logic: 
- The group manager's name is listed in the member list, but the button label say 'Leave' instead of 'Remove' 

For the one manager use case:: 
- Add Logic: the Leave confirmation dialog will have an additional sentence explaining the restriction and the confirmation button will be disabled. 

[mockup]
![image](https://user-images.githubusercontent.com/92342777/147955362-a2da71f1-bce8-4599-a162-acaedfb90a1b.png)

**Comment by Hanal-code** [comment]
Member list table shouldn't have the pagination row. Please remove it.
![image](https://user-images.githubusercontent.com/92342777/147959839-bb4cb486-b273-402a-916f-48cacdf0be9f.png)

**Comment by Hanal-code** [comment]
When do we start seeing the profile image from Google in the member module?

**Comment by josebui** [comment]
@Hanal-code Not sure, defenitely not in the scope of this task. Feel free to create a separate issue for this so that we can track it
